#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    l = []
    for j in range(len(arr)):
        s = sum(arr) - arr[j]
        l.append(s)
    print(min(l),max(l))


if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
